/**
 * oshidori-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Keep {
    keepId?: string;

    name: string;

    title?: string;

    description?: string;

    imageUrl?: string;

    eval?: any;

    userId?: string;

    talkId?: string;

    taskId?: string;

    createDateTime?: string;

    createUserId?: string;

    updateDateTime?: string;

    updateUserId?: string;

    deleteDateTime?: string;

    deleteUserId?: string;

    isDeleted?: string;

}
