/**
 * oshidori-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Task {
    taskId: string;

    title: string;

    description?: string;

    limit?: string;

    tags?: models.TaskTags;

    imageUrl?: string;

    selectedKeepId?: string;

    groupId?: string;

    ownerId?: string;

    createDateTime?: string;

    createUserId?: string;

    updateDateTime?: string;

    updateUserId?: string;

    deleteDateTime?: string;

    deleteUserId?: string;

    isDeleted?: string;

}
