/**
 * oshidori-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Group {
    groupId: string;

    partnerName?: string;

    thema?: any;

    members?: Array<models.GroupMembers>;

    createDateTime?: string;

    createUserId?: string;

    updateDateTime?: string;

    updateUserId?: string;

    deleteDateTime?: string;

    deleteUserId?: string;

    isDeleted?: string;

}
